'''
Problem #2:   
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

https://projecteuler.net/problem=2

2, 5, 8, 11

3n+2 
'''

def get_even_fibonacci_sum(l):
    s = 0
    n1 = 0
    n2 = 1
    while n2 < l:
        n3 = n2 + n1
        if not n3 % 2:
            s += n3
    n1, n2 = n2, n3
    return s

def main():
    l = 4000000
    s = get_even_fibonacci_sum(l)
    print (s)

if __name__ == "__main__":
    main()